name: SylphEvents
version: '${version}'
main: com.sylphmc.events.core.SylphEvents
api-version: 1.18
load: POSTWORLD
authors: [ Racci ]
depend: [ RacciCore, Sylph ]
softdepend: [ EcoEnchants, Citizens ]